- id: doi:10.1101/2023.11.26.568752
  image: "images/Publications/Giotto_Suite.png"
  tags:
    - Giotto Suite
    - spatial omics

- id: doi:10.3389/fendo.2022.1044670
  image: "images/Publications/TME.png"
  tags:
    - breast cancer
    - metabolism

- id: doi:10.1038/s43018-022-00427-5
  image: "images/Publications/nb_lineages.png"
  tags:
    - neuroblastoma
    - cell states

- id: doi:10.1186/s13059-021-02286-2
  image: "images/Publications/giotto_example.PNG"
  tags:
    - spatial transcriptomics
    - Giotto

- id: doi:10.1038/s41467-022-28616-x
  image: "images/Publications/fetal_liver.PNG"
  tags:
    - single cell
    - stem cell biology

- id: doi:10.1002/cpz1.405
  image: "images/Publications/Giotto_logo2.png"
  tags:
    - spatial transcriptomics
    - Giotto


- id: doi:10.1101/gr.275224.121
  image: "images/Publications/Spatial_advances.PNG"
  tags:
    - spatial transcriptomics
    - review


- id: doi:10.1038/s41586-019-1049-y
  image: "images/Publications/Seqfish_ligand.PNG"
  tags:
    - single cell
    - imaging


- id: doi:10.1016/j.ccell.2019.11.003
  image: "images/Publications/summary_CDK7_Zhang.png"
  tags:
    - Single cell
    - Oncology


- id: doi:10.1038/s41586-019-1472-0
  image: "images/Publications/summary_BORIS_Debruyne.png"
  tags:
    - single cell
    - 3D Chromatin
    - Oncology


- id: doi:10.1038/s41467-019-09703-y
  image: "images/Publications/summary_CDK12_Krajewska.png"
  tags:
    - transcript processing
    - Oncology

